on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java-version: [ 8, 11, 17 ]
        targets:
          - "__.publishLocal testRepo"
          - "itest[0.11.0-M4].test"
          - "itest[0.10.0].test"
          - "itest[0.9.10].test"
          - "itest[0.9.9].test"
          - "itest[0.9.8].test"

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'windows-latest' }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}

      - run: ./millw -i -k ${{ matrix.targets }}
        if: matrix.os != 'windows-latest'
      - run: .\millw.bat -i -k ${{ matrix.targets }}
        if: matrix.os == 'windows-latest'

      - run: ./millw -i -j 0 -k __.scoverage.xmlReport
        if: matrix.os != 'windows-latest'
      - run: ./millw.bat -i -j 0 -k __.scoverage.xmlReport
        if: matrix.os == 'windows-latest'

      - name: Upload scoverage reports to codecov.io
        uses: codecov/codecov-action@v1
        with:
          file: ./out/*/scoverage/xmlReport/dest/scoverage.xml
        continue-on-error: true
